import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

import { Footer } from "./components/footer";
import { Header } from "./components/navbar";
import { C_CTA } from "./components/contact_cta";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ECC Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="bg-ecc_white text-ecc_black">
      <body className={inter.className}>
        <Header />
        {children}
        <C_CTA />
        <Footer />
      </body>
    </html>
  );
}
